import { createAdminClient } from './supabase'

const SCOPES = ['pendaftaran:read','pendaftaran:sensitive:read','pendaftaran:documents:read','siswa:read','kelas:read','pendaftaran:milestone:update'] as const
type Scope=(typeof SCOPES)[number]
type Ctx={integration:any;token:any;admin:any;requestId:string;started:number;tokenHash:string}
const MAX_PAGE=200, DEFAULT_PAGE=100

const enc=new TextEncoder()
function b64url(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64json(v:unknown){return b64url(enc.encode(JSON.stringify(v)))}
function unb64json(v:string){try{const p=v.replace(/-/g,'+').replace(/_/g,'/');const raw=atob(p+'='.repeat((4-p.length%4)%4));const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}catch{return null}}
async function sha256(s:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(s));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hmac(keyHex:string,s:string){const key=Uint8Array.from(keyHex.match(/.{2}/g)!.map(x=>parseInt(x,16)));const k=await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(new Uint8Array(await crypto.subtle.sign('HMAC',k,enc.encode(s))))}
function json(body:unknown,status=200,headers:Record<string,string>={}){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff',...headers}})}
function err(code:string,message:string,status:number,requestId:string,extra:Record<string,unknown>={},headers:Record<string,string>={}){return json({error:{code,message,request_id:requestId,...extra}},status,headers)}
function has(ctx:Ctx,s:Scope){return (ctx.integration.scopes||[]).includes(s)}
export function allowed(ctx:Ctx,dept?:string|null,year?:string|null){const ds:string[]=ctx.integration.department_ids||[],ys:string[]=ctx.integration.academic_year_ids||[];return (!ds.length||!!dept&&ds.includes(dept))&&(!ys.length||!!year&&ys.includes(year))}
export function uuid(v:string|null){return !!v&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)}
function page(url:URL){const n=Number(url.searchParams.get('limit')||DEFAULT_PAGE);if(!Number.isInteger(n)||n<1||n>MAX_PAGE)throw new Error('LIMIT');return n}
function scopeFingerprint(ctx:Ctx){return JSON.stringify({s:[...(ctx.integration.scopes||[])].sort(),d:[...(ctx.integration.department_ids||[])].sort(),y:[...(ctx.integration.academic_year_ids||[])].sort()})}
function filterFingerprint(u:URL){return JSON.stringify([...u.searchParams.entries()].filter(([k])=>k!=='cursor'&&k!=='limit'&&k!=='checkpoint').sort())}
async function readCursor(v:string|null,kind:string,ctx:Ctx,filters:string){if(!v)return null;const [payload,sig]=v.split('.');if(!payload||!sig||await hmac(ctx.tokenHash,payload)!==sig)throw new Error('CURSOR');const x=unb64json(payload);if(!x||x.v!==2||x.kind!==kind||x.i!==ctx.integration.id||x.scope!==scopeFingerprint(ctx)||x.filters!==filters)throw new Error('CURSOR');return x}
async function nextCursor(kind:string,ctx:Ctx,filters:string,p:Record<string,unknown>){const payload=b64json({v:2,kind,i:ctx.integration.id,scope:scopeFingerprint(ctx),filters,...p});return `${payload}.${await hmac(ctx.tokenHash,payload)}`}

async function rate(admin:any,bucket:string,limit:number,seconds:number){const {data}=await (admin.rpc as any)('integration_rate_limit_hit',{p_bucket:bucket,p_limit:limit,p_window_seconds:seconds});return data?.[0]||{allowed:true,remaining:0,retry_after:seconds}}
export async function authenticateIntegration(request:Request):Promise<Ctx|Response>{
 const requestId=crypto.randomUUID(),started=Date.now(),admin=createAdminClient();const raw=request.headers.get('authorization'),token=raw?.replace(/^Bearer\s+/i,'').trim()
 if(!token){const r=await rate(admin,'invalid:missing',20,60);return r.allowed?err('unauthorized','Bearer token diperlukan',401,requestId):err('rate_limited','Terlalu banyak percobaan autentikasi',429,requestId,{retry_after:r.retry_after},{'Retry-After':String(r.retry_after)})}
 const prefix=token.slice(0,12),tokenHash=await sha256(token);const {data:t}=await (admin.from('integration_tokens') as any).select('id,integration_id,token_prefix,expires_at,revoked_at').eq('token_hash',tokenHash).maybeSingle()
 if(!t){const r=await rate(admin,`invalid:${prefix}`,20,60);return r.allowed?err('unauthorized','Token integrasi tidak valid',401,requestId):err('rate_limited','Terlalu banyak percobaan autentikasi',429,requestId,{retry_after:r.retry_after},{'Retry-After':String(r.retry_after)})}
 const {data:i}=await (admin.from('integration_apps') as any).select('id,name,active,scopes,department_ids,academic_year_ids,expires_at').eq('id',t.integration_id).maybeSingle();const now=Date.now()
 if(!i||!i.active||t.revoked_at||(t.expires_at&&Date.parse(t.expires_at)<=now)||(i.expires_at&&Date.parse(i.expires_at)<=now))return err('unauthorized','Token kedaluwarsa, dicabut, atau integrasi nonaktif',401,requestId)
 const r=await rate(admin,`integration:${i.id}`,300,60);if(!r.allowed)return err('rate_limited','Batas permintaan terlampaui',429,requestId,{retry_after:r.retry_after},{'Retry-After':String(r.retry_after)})
 await Promise.all([(admin.from('integration_tokens') as any).update({last_used_at:new Date().toISOString()}).eq('id',t.id),(admin.from('integration_apps') as any).update({last_used_at:new Date().toISOString()}).eq('id',i.id)])
 return {integration:i,token:t,admin,requestId,started,tokenHash}
}
export async function done(ctx:Ctx,route:string,response:Response){try{await (ctx.admin.from('integration_api_usage') as any).insert({integration_id:ctx.integration.id,route,request_id:ctx.requestId,status:response.status,duration_ms:Date.now()-ctx.started})}catch{}response.headers.set('X-Request-ID',ctx.requestId);return response}
export function need(ctx:Ctx,s:Scope){return has(ctx,s)?null:err('forbidden',`Scope ${s} diperlukan`,403,ctx.requestId)}

const BASE='id,nis,nama,jenis_kelamin,tempat_lahir,tanggal_lahir,agama,alamat,telepon,email,status,angkatan_id,created_at,departemen_id,terverifikasi'
const DETAIL='id,siswa_id,pendaftaran_id,tahun_ajaran_id,jenis_pendaftaran,nik,no_kk,kategori,status_asrama,anak_ke,jumlah_bersaudara,tinggi_badan_cm,berat_badan_kg,lingkar_kepala_cm,ukuran_baju,penyakit_pernah_diderita,jarak_rumah_km,waktu_perjalanan_menit,transportasi,nama_ayah,nik_ayah,tempat_lahir_ayah,tanggal_lahir_ayah,pendidikan_ayah,pekerjaan_ayah,penghasilan_ayah,telepon_ayah,alamat_ayah,nama_ibu,nik_ibu,tempat_lahir_ibu,tanggal_lahir_ibu,pendidikan_ibu,pekerjaan_ibu,penghasilan_ibu,telepon_ibu,alamat_ibu,telepon_ortu,alamat_ortu,asal_sekolah,kelas_terakhir,alasan_pindah,alamat_sekolah_asal,kabupaten_sekolah_asal,kecamatan_sekolah_asal,kelurahan_sekolah_asal,kemampuan_iqro,membaca_latin,menulis_latin,hafalan_quran,dokumen_kk_path,dokumen_akta_path,dokumen_rapor_path,dokumen_ijazah_path,spmb_tanggal_tes,spmb_tanggal_lulus,spmb_tanggal_daftar_ulang,spmb_verifikasi_status,spmb_verifikasi_at'
async function pathVersion(path:string){return (await sha256(path)).slice(0,24)}
async function docs(pid:string,d:any){const rows=[['kk',d.dokumen_kk_path],['akta',d.dokumen_akta_path],['rapor',d.dokumen_rapor_path],['ijazah',d.dokumen_ijazah_path]].filter(x=>x[1]);return Promise.all(rows.map(async([kind,path])=>({id:`${pid}.${kind}`,jenis:kind,nama_file:String(path).split('/').pop(),mime_type:null,ukuran:null,version:await pathVersion(String(path)),download_path:`/api/v1/documents/${pid}.${kind}`})))}
async function payment(ctx:Ctx,s:any){const {data,error}=await (ctx.admin.rpc as any)('integration_registration_payment_status',{p_siswa_id:s.id,p_departemen_id:s.departemen_id,p_created_at:s.created_at});if(error)return {status:'tidak_tersedia',tanggal_bayar:null,jumlah:null,gratis_gelombang_pertama:false};const p=Array.isArray(data)?data[0]:data;return {status:p?.status||'belum_tercatat',tanggal_bayar:p?.tanggal_bayar||null,jumlah:p?.jumlah??null,gratis_gelombang_pertama:!!p?.gratis_gelombang_pertama}}
async function registration(s:any,d:any,ctx:Ctx){const out:any={id:d.pendaftaran_id,siswa_id:s.status==='calon'?null:s.id,status:s.status,tanggal_pendaftaran:s.created_at,unit:{id:s.departemen_id},tahun_ajaran:{id:d.tahun_ajaran_id},angkatan:{id:s.angkatan_id},identitas:{nama:s.nama,jenis_kelamin:s.jenis_kelamin},jenis_pendaftaran:d.jenis_pendaftaran,kategori:d.kategori,status_asrama:d.status_asrama,tanggal_tes:d.spmb_tanggal_tes,tanggal_kelulusan:d.spmb_tanggal_lulus,tanggal_daftar_ulang:d.spmb_tanggal_daftar_ulang,verifikasi:{status:d.spmb_verifikasi_status,waktu:d.spmb_verifikasi_at},pembayaran_pendaftaran:await payment(ctx,s)}
 if(has(ctx,'pendaftaran:sensitive:read'))out.data_sensitif={nik:d.nik,no_kk:d.no_kk,tempat_lahir:s.tempat_lahir,tanggal_lahir:s.tanggal_lahir,agama:s.agama,alamat:s.alamat,telepon:s.telepon,email:s.email,anak_ke:d.anak_ke,jumlah_bersaudara:d.jumlah_bersaudara,tinggi_badan_cm:d.tinggi_badan_cm,berat_badan_kg:d.berat_badan_kg,lingkar_kepala_cm:d.lingkar_kepala_cm,ukuran_baju:d.ukuran_baju,penyakit_pernah_diderita:d.penyakit_pernah_diderita,jarak_rumah_km:d.jarak_rumah_km,waktu_perjalanan_menit:d.waktu_perjalanan_menit,transportasi:d.transportasi,orang_tua:{ayah:{nama:d.nama_ayah,nik:d.nik_ayah,tempat_lahir:d.tempat_lahir_ayah,tanggal_lahir:d.tanggal_lahir_ayah,pendidikan:d.pendidikan_ayah,pekerjaan:d.pekerjaan_ayah,penghasilan:d.penghasilan_ayah,telepon:d.telepon_ayah,alamat:d.alamat_ayah},ibu:{nama:d.nama_ibu,nik:d.nik_ibu,tempat_lahir:d.tempat_lahir_ibu,tanggal_lahir:d.tanggal_lahir_ibu,pendidikan:d.pendidikan_ibu,pekerjaan:d.pekerjaan_ibu,penghasilan:d.penghasilan_ibu,telepon:d.telepon_ibu,alamat:d.alamat_ibu},telepon:d.telepon_ortu,alamat:d.alamat_ortu},sekolah_asal:{nama:d.asal_sekolah,kelas_terakhir:d.kelas_terakhir,alasan_pindah:d.alasan_pindah,alamat:d.alamat_sekolah_asal,kabupaten:d.kabupaten_sekolah_asal,kecamatan:d.kecamatan_sekolah_asal,kelurahan:d.kelurahan_sekolah_asal},kemampuan:{iqro:d.kemampuan_iqro,membaca_latin:d.membaca_latin,menulis_latin:d.menulis_latin,hafalan_quran:d.hafalan_quran}}
 if(has(ctx,'pendaftaran:documents:read'))out.dokumen=await docs(d.pendaftaran_id,d);return out}
async function fetchRegistration(ctx:Ctx,id:string){const {data:d}=await (ctx.admin.from('siswa_detail') as any).select(DETAIL).eq('pendaftaran_id',id).maybeSingle();if(!d)return null;const {data:s}=await ctx.admin.from('siswa').select(BASE).eq('id',d.siswa_id).maybeSingle();if(!s||!allowed(ctx,s.departemen_id,d.tahun_ajaran_id))return null;return registration(s,d,ctx)}

export async function handleList(request:Request,type:'pendaftaran'|'siswa'|'kelas'){const a=await authenticateIntegration(request);if(a instanceof Response)return a;const ctx=a,route=`/api/v1/${type}`,req=need(ctx,type==='pendaftaran'?'pendaftaran:read':type==='siswa'?'siswa:read':'kelas:read');if(req)return done(ctx,route,req)
 try{const u=new URL(request.url),lim=page(u),filters=filterFingerprint(u),c=await readCursor(u.searchParams.get('cursor'),`list:${type}`,ctx,filters),after=c?.after||'';let source:any[]=[];let items:any[]=[]
 if(type==='pendaftaran'){let q=(ctx.admin.from('siswa_detail') as any).select(DETAIL).not('pendaftaran_id','is',null).order('pendaftaran_id').limit(Math.min(1000,lim*5+1));if(after)q=q.gt('pendaftaran_id',after);const year=u.searchParams.get('tahun_ajaran_id');if(year){if(!uuid(year))throw new Error('PARAM');if(ctx.integration.academic_year_ids?.length&&!ctx.integration.academic_year_ids.includes(year))return done(ctx,route,err('filter_out_of_scope','Tahun ajaran di luar cakupan token',403,ctx.requestId));q=q.eq('tahun_ajaran_id',year)}const {data,error}=await q;if(error)throw error;source=data||[];const ids=source.map((d:any)=>d.siswa_id);const {data:ss}=ids.length?await ctx.admin.from('siswa').select(BASE).in('id',ids):{data:[]};const sm=new Map((ss||[]).map((s:any)=>[s.id,s]));const visible=source.map((d:any)=>[sm.get(d.siswa_id),d]).filter(([s,d]:any)=>s&&allowed(ctx,s.departemen_id,d.tahun_ajaran_id));for(const [s,d] of visible.slice(0,lim+1) as any[])items.push(await registration(s,d,ctx))}
 else if(type==='siswa'){let q=ctx.admin.from('siswa').select(BASE).neq('status','calon').order('id').limit(Math.min(1000,lim*5+1));if(after)q=q.gt('id',after);const dept=u.searchParams.get('departemen_id');if(dept){if(!uuid(dept))throw new Error('PARAM');if(ctx.integration.department_ids?.length&&!ctx.integration.department_ids.includes(dept))return done(ctx,route,err('filter_out_of_scope','Unit di luar cakupan token',403,ctx.requestId));q=q.eq('departemen_id',dept)}if(u.searchParams.get('status'))q=q.eq('status',u.searchParams.get('status'));const {data,error}=await q;if(error)throw error;source=data||[];for(const s of source){if(ctx.integration.department_ids?.length&&!ctx.integration.department_ids.includes(s.departemen_id))continue;let years:any[]=[];if(ctx.integration.academic_year_ids?.length){const {data:rels}=await ctx.admin.from('kelas_siswa').select('tahun_ajaran_id').eq('siswa_id',s.id);years=(rels||[]).map((r:any)=>r.tahun_ajaran_id);if(!years.some(y=>ctx.integration.academic_year_ids.includes(y)))continue}items.push({id:s.id,nis:s.nis,nama:s.nama,jenis_kelamin:s.jenis_kelamin,status:s.status,unit:{id:s.departemen_id},angkatan:{id:s.angkatan_id},terverifikasi:s.terverifikasi,created_at:s.created_at});if(items.length>lim)break}}
 else {let q=ctx.admin.from('kelas').select('id,nama,tingkat_id,departemen_id,kapasitas,aktif').order('id').limit(Math.min(1000,lim*5+1));if(after)q=q.gt('id',after);const dept=u.searchParams.get('departemen_id');if(dept){if(!uuid(dept))throw new Error('PARAM');if(ctx.integration.department_ids?.length&&!ctx.integration.department_ids.includes(dept))return done(ctx,route,err('filter_out_of_scope','Unit di luar cakupan token',403,ctx.requestId));q=q.eq('departemen_id',dept)}const {data,error}=await q;if(error)throw error;source=data||[];for(const k of source){if(ctx.integration.department_ids?.length&&!ctx.integration.department_ids.includes(k.departemen_id))continue;if(ctx.integration.academic_year_ids?.length){const {data:r}=await ctx.admin.from('kelas_siswa').select('tahun_ajaran_id').eq('kelas_id',k.id).in('tahun_ajaran_id',ctx.integration.academic_year_ids).limit(1);if(!r?.length)continue}items.push(k);if(items.length>lim)break}}
 const more=items.length>lim;items=items.slice(0,lim);const last:any=items.at(-1);return done(ctx,route,json({data:items,pagination:{limit:lim,has_more:more,next_cursor:more&&last?await nextCursor(`list:${type}`,ctx,filters,{after:last.id}):null}}))}catch(e){const code=e instanceof Error&&e.message==='LIMIT'?'invalid_limit':e instanceof Error&&e.message==='PARAM'?'invalid_parameter':'invalid_cursor';return done(ctx,route,err(code,'Parameter request tidak valid',400,ctx.requestId))}}

export async function handleDetail(request:Request,type:'pendaftaran'|'siswa',id:string){const a=await authenticateIntegration(request);if(a instanceof Response)return a;const ctx=a,route=`/api/v1/${type}/:id`,req=need(ctx,type==='pendaftaran'?'pendaftaran:read':'siswa:read');if(req)return done(ctx,route,req);if(!uuid(id))return done(ctx,route,err('invalid_id','ID tidak valid',400,ctx.requestId));if(type==='pendaftaran'){const x=await fetchRegistration(ctx,id);return done(ctx,route,x?json({data:x}):err('not_found','Data tidak ditemukan atau di luar cakupan',404,ctx.requestId))}const {data:s}=await ctx.admin.from('siswa').select(BASE).eq('id',id).neq('status','calon').maybeSingle();if(!s||(ctx.integration.department_ids?.length&&!ctx.integration.department_ids.includes(s.departemen_id)))return done(ctx,route,err('not_found','Data tidak ditemukan atau di luar cakupan',404,ctx.requestId));const {data:ks}=await ctx.admin.from('kelas_siswa').select('id,kelas_id,tahun_ajaran_id,aktif').eq('siswa_id',id).eq('aktif',true);const visible=(ks||[]).filter((x:any)=>!ctx.integration.academic_year_ids?.length||ctx.integration.academic_year_ids.includes(x.tahun_ajaran_id));if(ctx.integration.academic_year_ids?.length&&!visible.length)return done(ctx,route,err('not_found','Data tidak ditemukan atau di luar cakupan',404,ctx.requestId));return done(ctx,route,json({data:{...s,kelas_aktif:visible}}))}

export async function handleClassStudents(request:Request,id:string){const a=await authenticateIntegration(request);if(a instanceof Response)return a;const ctx=a,route='/api/v1/kelas/:id/siswa',req=need(ctx,'kelas:read')||need(ctx,'siswa:read');if(req)return done(ctx,route,req);if(!uuid(id))return done(ctx,route,err('invalid_id','ID tidak valid',400,ctx.requestId));const {data:k}=await ctx.admin.from('kelas').select('id,nama,departemen_id,aktif').eq('id',id).maybeSingle();if(!k||(ctx.integration.department_ids?.length&&!ctx.integration.department_ids.includes(k.departemen_id)))return done(ctx,route,err('not_found','Kelas tidak ditemukan atau di luar cakupan',404,ctx.requestId));const {data:rels}=await ctx.admin.from('kelas_siswa').select('siswa_id,tahun_ajaran_id').eq('kelas_id',id).eq('aktif',true);const ids=(rels||[]).filter((r:any)=>!ctx.integration.academic_year_ids?.length||ctx.integration.academic_year_ids.includes(r.tahun_ajaran_id)).map((r:any)=>r.siswa_id);const {data:ss}=ids.length?await ctx.admin.from('siswa').select('id,nis,nama,status,departemen_id').in('id',ids):{data:[]};return done(ctx,route,json({data:ss||[]}))}

export async function handleSync(request:Request,type:'pendaftaran'|'siswa'|'kelas'){const a=await authenticateIntegration(request);if(a instanceof Response)return a;const ctx=a,route=`/api/v1/sync/${type}`,req=need(ctx,type==='pendaftaran'?'pendaftaran:read':type==='siswa'?'siswa:read':'kelas:read');if(req)return done(ctx,route,req)
 try{const u=new URL(request.url),lim=page(u),filters=filterFingerprint(u),c=await readCursor(u.searchParams.get('cursor'),`sync:${type}`,ctx,filters);let checkpoint:number,after:number;if(!c){const {data:max}=await (ctx.admin.from('integration_change_log') as any).select('seq').order('seq',{ascending:false}).limit(1);checkpoint=max?.[0]?.seq||0;after=Number(u.searchParams.get('checkpoint')||0);if(!Number.isSafeInteger(after)||after<0)throw new Error('PARAM')}else{checkpoint=c.checkpoint;after=c.after}const minCut=new Date(Date.now()-90*86400000).toISOString();const {data:minRows}=await (ctx.admin.from('integration_change_log') as any).select('seq').gte('changed_at',minCut).order('seq').limit(1);const minSeq=minRows?.[0]?.seq||0;if(after&&after<minSeq)return done(ctx,route,err('checkpoint_expired','Checkpoint sudah melewati retensi change log; lakukan bootstrap ulang',410,ctx.requestId));const {data,error}=await (ctx.admin.from('integration_change_log') as any).select('seq,object_type,object_id,change_type,department_id,academic_year_id,previous_department_id,previous_academic_year_id,changed_at').gt('seq',after).lte('seq',checkpoint).in('object_type',type==='pendaftaran'?['pendaftaran','dokumen']:[type]).order('seq').limit(Math.min(1000,lim*5+1));if(error)throw error;const rows=(data||[]).filter((r:any)=>allowed(ctx,r.department_id,r.academic_year_id)||allowed(ctx,r.previous_department_id,r.previous_academic_year_id));const chosen=rows.slice(0,lim),changes=[];for(const r of chosen){let data:any=null,change=r.change_type;if(r.object_type==='pendaftaran'||r.object_type==='dokumen')data=await fetchRegistration(ctx,r.object_id);else if(r.object_type==='siswa'){const {data:s}=await ctx.admin.from('siswa').select(BASE).eq('id',r.object_id).maybeSingle();data=s&&s.status!=='calon'&&(!ctx.integration.department_ids?.length||ctx.integration.department_ids.includes(s.departemen_id))?s:null}else{const {data:k}=await ctx.admin.from('kelas').select('id,nama,tingkat_id,departemen_id,kapasitas,aktif').eq('id',r.object_id).maybeSingle();data=k&&(!ctx.integration.department_ids?.length||ctx.integration.department_ids.includes(k.departemen_id))?k:null}if(!data&&change==='upsert')change='scope_exit';changes.push({id:r.object_id,object_type:r.object_type,change,version:r.seq,changed_at:r.changed_at,data})}const last=chosen.at(-1),more=rows.length>lim;return done(ctx,route,json({data:changes,sync:{checkpoint,checkpoint_safe:!more,next_cursor:more&&last?await nextCursor(`sync:${type}`,ctx,filters,{checkpoint,after:last.seq}):null,has_more:more,retention_days:90}}))}catch(e){return done(ctx,route,err(e instanceof Error&&e.message==='LIMIT'?'invalid_limit':e instanceof Error&&e.message==='PARAM'?'invalid_parameter':'invalid_cursor','Cursor atau parameter sinkronisasi tidak valid',400,ctx.requestId))}}

export async function handleDocument(request:Request,docId:string){const a=await authenticateIntegration(request);if(a instanceof Response)return a;const ctx=a,route='/api/v1/documents/:id',req=need(ctx,'pendaftaran:read')||need(ctx,'pendaftaran:documents:read');if(req)return done(ctx,route,req);const m=/^([0-9a-f-]{36})\.(kk|akta|rapor|ijazah)$/i.exec(docId);if(!m)return done(ctx,route,err('invalid_id','ID dokumen tidak valid',400,ctx.requestId));const pid=m[1],kind=m[2].toLowerCase();const {data:d}=await (ctx.admin.from('siswa_detail') as any).select(`siswa_id,pendaftaran_id,tahun_ajaran_id,dokumen_${kind}_path`).eq('pendaftaran_id',pid).maybeSingle();const {data:s}=d?await ctx.admin.from('siswa').select('departemen_id').eq('id',d.siswa_id).maybeSingle():{data:null};const path=d?.[`dokumen_${kind}_path`];if(!d||!s||!path||!allowed(ctx,s.departemen_id,d.tahun_ajaran_id))return done(ctx,route,err('not_found','Dokumen tidak ditemukan atau di luar cakupan',404,ctx.requestId));const {data:signed,error}=await ctx.admin.storage.from('pmb-dokumen').createSignedUrl(path,60);if(error||!signed?.signedUrl)return done(ctx,route,err('temporary_failure','Gagal menerbitkan akses dokumen',503,ctx.requestId));return done(ctx,route,json({data:{id:docId,version:await pathVersion(path),expires_in:60,url:signed.signedUrl}}))}
