import {createServerFn} from '@tanstack/react-start'; import {authMiddleware,requireContext,requireRole} from './auth'; import {createAdminClient} from './supabase';
const ALLOWED=['pendaftaran:read','pendaftaran:sensitive:read','pendaftaran:documents:read','siswa:read','kelas:read','pendaftaran:milestone:update'];
async function hash(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function token(){const a=new Uint8Array(32);crypto.getRandomValues(a);return 'hat_live_'+[...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function adminCtx(context:unknown){const c=requireContext(context),db=createAdminClient();await requireRole(db,c.userId,['admin']);return {c,db}}
function validateScopes(scopes:string[]){if(scopes.some(x=>!ALLOWED.includes(x)))throw new Error('Scope tidak valid');if((scopes.includes('pendaftaran:sensitive:read')||scopes.includes('pendaftaran:documents:read'))&&!scopes.includes('pendaftaran:read'))throw new Error('Scope sensitif/dokumen memerlukan pendaftaran:read')}
export const listIntegrationOptions=createServerFn({method:'GET'}).middleware([authMiddleware]).handler(async({context})=>{const {db}=await adminCtx(context);const [{data:departments,error:de},{data:years,error:ye}]=await Promise.all([db.from('departemen').select('id,nama,kode').eq('aktif',true).order('nama'),db.from('tahun_ajaran').select('id,nama,aktif').order('nama',{ascending:false})]);if(de)throw de;if(ye)throw ye;return {departments:departments||[],academicYears:years||[]}});
export const listIntegrations=createServerFn({method:'GET'}).middleware([authMiddleware]).handler(async({context})=>{const {db}=await adminCtx(context);const {data,error}=await (db.from('integration_apps') as any).select('id,name,active,scopes,department_ids,academic_year_ids,expires_at,created_at,updated_at,last_used_at,integration_tokens(id,token_prefix,expires_at,revoked_at,created_at,last_used_at)').order('created_at',{ascending:false});if(error)throw error;return data||[]});
export const createIntegration=createServerFn({method:'POST'}).middleware([authMiddleware]).inputValidator((x:{name:string;scopes:string[];department_ids?:string[];academic_year_ids?:string[];expires_at?:string|null})=>x).handler(async({data,context})=>{const {c,db}=await adminCtx(context);const scopes=[...new Set(data.scopes||[])];if(!data.name?.trim())throw new Error('Nama integrasi wajib diisi');validateScopes(scopes);const {data:i,error}=await (db.from('integration_apps') as any).insert({name:data.name.trim(),scopes,department_ids:data.department_ids||[],academic_year_ids:data.academic_year_ids||[],expires_at:data.expires_at||null,created_by:c.userId}).select('id').single();if(error)throw error;const raw=token(),prefix=raw.slice(0,16);await (db.from('integration_tokens') as any).insert({integration_id:i.id,token_prefix:prefix,token_hash:await hash(raw),expires_at:data.expires_at||null,created_by:c.userId});await (db.from('integration_audit_log') as any).insert({integration_id:i.id,actor_id:c.userId,action:'created',metadata:{scopes,department_ids:data.department_ids||[],academic_year_ids:data.academic_year_ids||[],expires_at:data.expires_at||null}});return {id:i.id,token:raw,prefix}});
export const updateIntegration=createServerFn({method:'POST'}).middleware([authMiddleware]).inputValidator((x:{id:string;active?:boolean;scopes?:string[];department_ids?:string[];academic_year_ids?:string[];expires_at?:string|null})=>x).handler(async({data,context})=>{const {c,db}=await adminCtx(context);if(data.scopes)validateScopes(data.scopes);const {data:before}=await (db.from('integration_apps') as any).select('active,scopes,department_ids,academic_year_ids,expires_at').eq('id',data.id).maybeSingle();if(!before)throw new Error('Integrasi tidak ditemukan');const patch:any={updated_at:new Date().toISOString()};for(const k of ['active','scopes','department_ids','academic_year_ids','expires_at'] as const)if(data[k]!==undefined)patch[k]=data[k];const {error}=await (db.from('integration_apps') as any).update(patch).eq('id',data.id);if(error)throw error;await (db.from('integration_audit_log') as any).insert({integration_id:data.id,actor_id:c.userId,action:'updated',metadata:{before,after:{...before,...patch}}});return {success:true}});
export const rotateIntegrationToken=createServerFn({method:'POST'}).middleware([authMiddleware]).inputValidator((x:{id:string})=>x).handler(async({data,context})=>{const {c,db}=await adminCtx(context);const {data:i}=await (db.from('integration_apps') as any).select('id,expires_at').eq('id',data.id).single();if(!i)throw new Error('Integrasi tidak ditemukan');await (db.from('integration_tokens') as any).update({revoked_at:new Date().toISOString()}).eq('integration_id',data.id).is('revoked_at',null);const raw=token();await (db.from('integration_tokens') as any).insert({integration_id:data.id,token_prefix:raw.slice(0,16),token_hash:await hash(raw),expires_at:i.expires_at,created_by:c.userId});await (db.from('integration_audit_log') as any).insert({integration_id:data.id,actor_id:c.userId,action:'token_rotated'});return {token:raw,prefix:raw.slice(0,16)}});
export const revokeIntegrationTokens=createServerFn({method:'POST'}).middleware([authMiddleware]).inputValidator((x:{id:string})=>x).handler(async({data,context})=>{const {c,db}=await adminCtx(context);await (db.from('integration_tokens') as any).update({revoked_at:new Date().toISOString()}).eq('integration_id',data.id).is('revoked_at',null);await (db.from('integration_audit_log') as any).insert({integration_id:data.id,actor_id:c.userId,action:'tokens_revoked'});return {success:true}});